# Site
name: "The Secret Herb"
title: "The Secret Herb"
description: "Brew Your Secret Bliss with Nature’s Herbal Kiss 🌿✨"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thesecretherb.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: the108matrix@gmail.com

# Authors
authors:
    aaina:
    name: Aaina
    display_name: Aaina
    avatar: 'assets/images/avatar.png'
    # email: the108matrix@gmail.com
    # web: 
    # twitter: 
    description: Aaina, a statistics graduate with a passion for natural remedies, blends analytical rigor with non-invasive alternative healing. Inspired by wellness experts, she explores ancient remedies to enhance health and vitality, always striving to deepen her knowledge and support your wellness journey.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
